Rename base to catalog
rmrk-team/evm pull request #139
Opened 2022-12-29 00:56 UTC by ThunderDeliverer

# Description

As we renamed `Base` to `Catalog` our contracts had to be updated.

# Actions

- Renamed smart contracts
- Updated references to `Base` with `Catalog`
- Updated NatSpec comments to reflect the changes
- Updated tests to reference `catalog` rather than `base`

# Checklist

- [x] Verified code additions
- [x] Updated NatSpec comments (if applicable)
- [x] Regenerated docs
- [x] Ran prettier
- [x] Added tests to fully cover the changes

2022-12-29 15:24 UTC, steven2308 requested changes
Minor camel case fix.

2022-12-29 15:24 UTC, steven2308 commented on contracts/RMRK/equippable/IRMRKEquippable.sol
> +     * @param targetcatalogAddress Address of the `Catalog` associated with the `Slot` part of the token
```suggestion
     * @param targetCatalogAddress Address of the `Catalog` associated with the `Slot` part of the token
```

2022-12-29 15:24 UTC, steven2308 commented on contracts/RMRK/equippable/IRMRKEquippable.sol
> +        address targetcatalogAddress,
```suggestion
        address targetCatalogAddress,
```

2022-12-29 15:24 UTC, steven2308 commented on contracts/RMRK/equippable/RMRKEquippable.sol
> +        address targetcatalogAddress = _catalogAddresses[assetId];
```suggestion
        address targetCatalogAddress = _catalogAddresses[assetId];
```

2022-12-29 15:24 UTC, steven2308 commented on contracts/RMRK/equippable/RMRKEquippable.sol
> +        Equipment memory equipment = _equipments[tokenId][targetcatalogAddress][
```suggestion
        Equipment memory equipment = _equipments[tokenId][targetCatalogAddress][
```

2022-12-29 15:24 UTC, steven2308 commented on contracts/RMRK/equippable/RMRKEquippable.sol
> +        delete _equipments[tokenId][targetcatalogAddress][slotPartId];
```suggestion
        delete _equipments[tokenId][targetCatalogAddress][slotPartId];
```

2022-12-29 15:24 UTC, steven2308 commented on contracts/RMRK/equippable/RMRKEquippable.sol
> +        address targetcatalogAddress,
```suggestion
        address targetCatalogAddress,
```

2022-12-29 15:24 UTC, steven2308 commented on contracts/RMRK/equippable/RMRKEquippable.sol
> +        return _equipments[tokenId][targetcatalogAddress][slotPartId];
```suggestion
        return _equipments[tokenId][targetCatalogAddress][slotPartId];
```

2022-12-29 15:24 UTC, steven2308 commented on contracts/RMRK/equippable/RMRKExternalEquip.sol
> +        delete _equipments[tokenId][targetcatalogAddress][slotPartId];
```suggestion
        delete _equipments[tokenId][targetCatalogAddress][slotPartId];
```

2022-12-29 15:24 UTC, steven2308 commented on contracts/RMRK/equippable/RMRKExternalEquip.sol
> +        address targetcatalogAddress = _catalogAddresses[assetId];
```suggestion
        address targetCatalogAddress = _catalogAddresses[assetId];
```

2022-12-29 15:24 UTC, steven2308 commented on contracts/RMRK/equippable/RMRKExternalEquip.sol
> +        Equipment memory equipment = _equipments[tokenId][targetcatalogAddress][
```suggestion
        Equipment memory equipment = _equipments[tokenId][targetCatalogAddress][
```

2022-12-29 15:24 UTC, steven2308 commented on contracts/RMRK/equippable/RMRKExternalEquip.sol
> +        address targetcatalogAddress,
```suggestion
        address targetCatalogAddress,
```

2022-12-29 15:24 UTC, steven2308 commented on contracts/RMRK/equippable/RMRKExternalEquip.sol
> +        return _equipments[tokenId][targetcatalogAddress][slotPartId];
```suggestion
        return _equipments[tokenId][targetCatalogAddress][slotPartId];
```

2022-12-30 15:22 UTC, stevyhacker approved these changes

2023-01-03 12:43 UTC, steven2308 approved these changes

2023-01-03 12:53 UTC, merged